// flow-typed signature: efcadcd3c0a528a9361c7351146c845a
// flow-typed version: <<STUB>>/promirepl_v^1.0.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promirepl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'promirepl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promirepl/bin/prominode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promirepl/bin/prominode.js' {
  declare module.exports: $Exports<'promirepl/bin/prominode'>;
}
declare module 'promirepl/index' {
  declare module.exports: $Exports<'promirepl'>;
}
declare module 'promirepl/index.js' {
  declare module.exports: $Exports<'promirepl'>;
}
