// flow-typed signature: d533189706bd2973c51e93522b703f92
// flow-typed version: <<STUB>>/soap-as-promised_v^1.16.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'soap-as-promised'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'soap-as-promised' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'soap-as-promised/soap-as-promised' {
  declare module.exports: any;
}

declare module 'soap-as-promised/test/client-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'soap-as-promised/soap-as-promised.js' {
  declare module.exports: $Exports<'soap-as-promised/soap-as-promised'>;
}
declare module 'soap-as-promised/test/client-test.js' {
  declare module.exports: $Exports<'soap-as-promised/test/client-test'>;
}
