// flow-typed signature: e5fbf3eb4a86fe33534fad08be702cdd
// flow-typed version: <<STUB>>/strong-soap_v^1.2.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strong-soap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'strong-soap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'strong-soap/example/json2xml' {
  declare module.exports: any;
}

declare module 'strong-soap/example/ntlm' {
  declare module.exports: any;
}

declare module 'strong-soap/example/stockquote' {
  declare module.exports: any;
}

declare module 'strong-soap/example/weather' {
  declare module.exports: any;
}

declare module 'strong-soap/example/xml' {
  declare module.exports: any;
}

declare module 'strong-soap/example/xml2json' {
  declare module.exports: any;
}

declare module 'strong-soap/example/xsds' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/base' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/client' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/globalize' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/http' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/element' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/helper' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/index' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/nscontext' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/qname' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/soap/body' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/soap/fault' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/soap/header' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/soap/headerFault' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/soap/soapElement' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/soap12/body' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/soap12/fault' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/soap12/header' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/soap12/headerFault' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/soap12/soapElement' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/typeRegistry' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/binding' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/definitions' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/documentation' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/fault' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/import' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/input' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/message' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/operation' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/output' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/parameter' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/part' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/port' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/portType' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/service' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/types' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/wsdl/wsdlElement' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xmlHandler' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/all' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/annotation' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/any' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/anyAttribute' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/attribute' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/attributeGroup' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/choice' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/complexContent' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/complexType' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/descriptor' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/documentation' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/element' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/extension' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/group' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/import' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/Include' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/key' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/keybase' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/keyref' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/list' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/restriction' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/schema' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/sequence' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/simpleContent' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/simpleType' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/union' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/unique' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/parser/xsd/xsdElement' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/security/BasicAuthSecurity' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/security/BearerSecurity' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/security/ClientSSLSecurity' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/security/ClientSSLSecurityPFX' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/security/index' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/security/NTLMSecurity' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/security/security' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/security/WSSecurity' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/security/WSSecurityCert' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/server' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/soap' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/soapModel' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/strip-bom' {
  declare module.exports: any;
}

declare module 'strong-soap/lib/utils' {
  declare module.exports: any;
}

declare module 'strong-soap/soap-stub' {
  declare module.exports: any;
}

declare module 'strong-soap/src/base' {
  declare module.exports: any;
}

declare module 'strong-soap/src/client' {
  declare module.exports: any;
}

declare module 'strong-soap/src/globalize' {
  declare module.exports: any;
}

declare module 'strong-soap/src/http' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/element' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/helper' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/index' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/nscontext' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/qname' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/soap/body' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/soap/fault' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/soap/header' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/soap/headerFault' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/soap/soapElement' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/soap12/body' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/soap12/fault' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/soap12/header' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/soap12/headerFault' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/soap12/soapElement' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/typeRegistry' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/binding' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/definitions' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/documentation' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/fault' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/import' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/input' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/message' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/operation' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/output' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/parameter' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/part' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/port' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/portType' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/service' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/types' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/wsdl/wsdlElement' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xmlHandler' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/all' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/annotation' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/any' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/anyAttribute' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/attribute' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/attributeGroup' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/choice' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/complexContent' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/complexType' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/descriptor' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/documentation' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/element' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/extension' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/group' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/import' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/include' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/key' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/keybase' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/keyref' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/list' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/restriction' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/schema' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/sequence' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/simpleContent' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/simpleType' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/union' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/unique' {
  declare module.exports: any;
}

declare module 'strong-soap/src/parser/xsd/xsdElement' {
  declare module.exports: any;
}

declare module 'strong-soap/src/security/BasicAuthSecurity' {
  declare module.exports: any;
}

declare module 'strong-soap/src/security/BearerSecurity' {
  declare module.exports: any;
}

declare module 'strong-soap/src/security/ClientSSLSecurity' {
  declare module.exports: any;
}

declare module 'strong-soap/src/security/ClientSSLSecurityPFX' {
  declare module.exports: any;
}

declare module 'strong-soap/src/security/index' {
  declare module.exports: any;
}

declare module 'strong-soap/src/security/NTLMSecurity' {
  declare module.exports: any;
}

declare module 'strong-soap/src/security/security' {
  declare module.exports: any;
}

declare module 'strong-soap/src/security/WSSecurity' {
  declare module.exports: any;
}

declare module 'strong-soap/src/security/WSSecurityCert' {
  declare module.exports: any;
}

declare module 'strong-soap/src/server' {
  declare module.exports: any;
}

declare module 'strong-soap/src/soap' {
  declare module.exports: any;
}

declare module 'strong-soap/src/soapModel' {
  declare module.exports: any;
}

declare module 'strong-soap/src/strip-bom' {
  declare module.exports: any;
}

declare module 'strong-soap/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'strong-soap/example/json2xml.js' {
  declare module.exports: $Exports<'strong-soap/example/json2xml'>;
}
declare module 'strong-soap/example/ntlm.js' {
  declare module.exports: $Exports<'strong-soap/example/ntlm'>;
}
declare module 'strong-soap/example/stockquote.js' {
  declare module.exports: $Exports<'strong-soap/example/stockquote'>;
}
declare module 'strong-soap/example/weather.js' {
  declare module.exports: $Exports<'strong-soap/example/weather'>;
}
declare module 'strong-soap/example/xml.js' {
  declare module.exports: $Exports<'strong-soap/example/xml'>;
}
declare module 'strong-soap/example/xml2json.js' {
  declare module.exports: $Exports<'strong-soap/example/xml2json'>;
}
declare module 'strong-soap/example/xsds.js' {
  declare module.exports: $Exports<'strong-soap/example/xsds'>;
}
declare module 'strong-soap/index' {
  declare module.exports: $Exports<'strong-soap'>;
}
declare module 'strong-soap/index.js' {
  declare module.exports: $Exports<'strong-soap'>;
}
declare module 'strong-soap/lib/base.js' {
  declare module.exports: $Exports<'strong-soap/lib/base'>;
}
declare module 'strong-soap/lib/client.js' {
  declare module.exports: $Exports<'strong-soap/lib/client'>;
}
declare module 'strong-soap/lib/globalize.js' {
  declare module.exports: $Exports<'strong-soap/lib/globalize'>;
}
declare module 'strong-soap/lib/http.js' {
  declare module.exports: $Exports<'strong-soap/lib/http'>;
}
declare module 'strong-soap/lib/parser/element.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/element'>;
}
declare module 'strong-soap/lib/parser/helper.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/helper'>;
}
declare module 'strong-soap/lib/parser/index.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/index'>;
}
declare module 'strong-soap/lib/parser/nscontext.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/nscontext'>;
}
declare module 'strong-soap/lib/parser/qname.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/qname'>;
}
declare module 'strong-soap/lib/parser/soap/body.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/soap/body'>;
}
declare module 'strong-soap/lib/parser/soap/fault.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/soap/fault'>;
}
declare module 'strong-soap/lib/parser/soap/header.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/soap/header'>;
}
declare module 'strong-soap/lib/parser/soap/headerFault.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/soap/headerFault'>;
}
declare module 'strong-soap/lib/parser/soap/soapElement.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/soap/soapElement'>;
}
declare module 'strong-soap/lib/parser/soap12/body.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/soap12/body'>;
}
declare module 'strong-soap/lib/parser/soap12/fault.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/soap12/fault'>;
}
declare module 'strong-soap/lib/parser/soap12/header.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/soap12/header'>;
}
declare module 'strong-soap/lib/parser/soap12/headerFault.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/soap12/headerFault'>;
}
declare module 'strong-soap/lib/parser/soap12/soapElement.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/soap12/soapElement'>;
}
declare module 'strong-soap/lib/parser/typeRegistry.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/typeRegistry'>;
}
declare module 'strong-soap/lib/parser/wsdl.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl'>;
}
declare module 'strong-soap/lib/parser/wsdl/binding.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/binding'>;
}
declare module 'strong-soap/lib/parser/wsdl/definitions.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/definitions'>;
}
declare module 'strong-soap/lib/parser/wsdl/documentation.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/documentation'>;
}
declare module 'strong-soap/lib/parser/wsdl/fault.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/fault'>;
}
declare module 'strong-soap/lib/parser/wsdl/import.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/import'>;
}
declare module 'strong-soap/lib/parser/wsdl/input.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/input'>;
}
declare module 'strong-soap/lib/parser/wsdl/message.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/message'>;
}
declare module 'strong-soap/lib/parser/wsdl/operation.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/operation'>;
}
declare module 'strong-soap/lib/parser/wsdl/output.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/output'>;
}
declare module 'strong-soap/lib/parser/wsdl/parameter.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/parameter'>;
}
declare module 'strong-soap/lib/parser/wsdl/part.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/part'>;
}
declare module 'strong-soap/lib/parser/wsdl/port.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/port'>;
}
declare module 'strong-soap/lib/parser/wsdl/portType.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/portType'>;
}
declare module 'strong-soap/lib/parser/wsdl/service.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/service'>;
}
declare module 'strong-soap/lib/parser/wsdl/types.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/types'>;
}
declare module 'strong-soap/lib/parser/wsdl/wsdlElement.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/wsdl/wsdlElement'>;
}
declare module 'strong-soap/lib/parser/xmlHandler.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xmlHandler'>;
}
declare module 'strong-soap/lib/parser/xsd.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd'>;
}
declare module 'strong-soap/lib/parser/xsd/all.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/all'>;
}
declare module 'strong-soap/lib/parser/xsd/annotation.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/annotation'>;
}
declare module 'strong-soap/lib/parser/xsd/any.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/any'>;
}
declare module 'strong-soap/lib/parser/xsd/anyAttribute.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/anyAttribute'>;
}
declare module 'strong-soap/lib/parser/xsd/attribute.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/attribute'>;
}
declare module 'strong-soap/lib/parser/xsd/attributeGroup.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/attributeGroup'>;
}
declare module 'strong-soap/lib/parser/xsd/choice.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/choice'>;
}
declare module 'strong-soap/lib/parser/xsd/complexContent.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/complexContent'>;
}
declare module 'strong-soap/lib/parser/xsd/complexType.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/complexType'>;
}
declare module 'strong-soap/lib/parser/xsd/descriptor.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/descriptor'>;
}
declare module 'strong-soap/lib/parser/xsd/documentation.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/documentation'>;
}
declare module 'strong-soap/lib/parser/xsd/element.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/element'>;
}
declare module 'strong-soap/lib/parser/xsd/extension.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/extension'>;
}
declare module 'strong-soap/lib/parser/xsd/group.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/group'>;
}
declare module 'strong-soap/lib/parser/xsd/import.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/import'>;
}
declare module 'strong-soap/lib/parser/xsd/Include.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/Include'>;
}
declare module 'strong-soap/lib/parser/xsd/key.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/key'>;
}
declare module 'strong-soap/lib/parser/xsd/keybase.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/keybase'>;
}
declare module 'strong-soap/lib/parser/xsd/keyref.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/keyref'>;
}
declare module 'strong-soap/lib/parser/xsd/list.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/list'>;
}
declare module 'strong-soap/lib/parser/xsd/restriction.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/restriction'>;
}
declare module 'strong-soap/lib/parser/xsd/schema.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/schema'>;
}
declare module 'strong-soap/lib/parser/xsd/sequence.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/sequence'>;
}
declare module 'strong-soap/lib/parser/xsd/simpleContent.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/simpleContent'>;
}
declare module 'strong-soap/lib/parser/xsd/simpleType.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/simpleType'>;
}
declare module 'strong-soap/lib/parser/xsd/union.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/union'>;
}
declare module 'strong-soap/lib/parser/xsd/unique.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/unique'>;
}
declare module 'strong-soap/lib/parser/xsd/xsdElement.js' {
  declare module.exports: $Exports<'strong-soap/lib/parser/xsd/xsdElement'>;
}
declare module 'strong-soap/lib/security/BasicAuthSecurity.js' {
  declare module.exports: $Exports<'strong-soap/lib/security/BasicAuthSecurity'>;
}
declare module 'strong-soap/lib/security/BearerSecurity.js' {
  declare module.exports: $Exports<'strong-soap/lib/security/BearerSecurity'>;
}
declare module 'strong-soap/lib/security/ClientSSLSecurity.js' {
  declare module.exports: $Exports<'strong-soap/lib/security/ClientSSLSecurity'>;
}
declare module 'strong-soap/lib/security/ClientSSLSecurityPFX.js' {
  declare module.exports: $Exports<'strong-soap/lib/security/ClientSSLSecurityPFX'>;
}
declare module 'strong-soap/lib/security/index.js' {
  declare module.exports: $Exports<'strong-soap/lib/security/index'>;
}
declare module 'strong-soap/lib/security/NTLMSecurity.js' {
  declare module.exports: $Exports<'strong-soap/lib/security/NTLMSecurity'>;
}
declare module 'strong-soap/lib/security/security.js' {
  declare module.exports: $Exports<'strong-soap/lib/security/security'>;
}
declare module 'strong-soap/lib/security/WSSecurity.js' {
  declare module.exports: $Exports<'strong-soap/lib/security/WSSecurity'>;
}
declare module 'strong-soap/lib/security/WSSecurityCert.js' {
  declare module.exports: $Exports<'strong-soap/lib/security/WSSecurityCert'>;
}
declare module 'strong-soap/lib/server.js' {
  declare module.exports: $Exports<'strong-soap/lib/server'>;
}
declare module 'strong-soap/lib/soap.js' {
  declare module.exports: $Exports<'strong-soap/lib/soap'>;
}
declare module 'strong-soap/lib/soapModel.js' {
  declare module.exports: $Exports<'strong-soap/lib/soapModel'>;
}
declare module 'strong-soap/lib/strip-bom.js' {
  declare module.exports: $Exports<'strong-soap/lib/strip-bom'>;
}
declare module 'strong-soap/lib/utils.js' {
  declare module.exports: $Exports<'strong-soap/lib/utils'>;
}
declare module 'strong-soap/soap-stub.js' {
  declare module.exports: $Exports<'strong-soap/soap-stub'>;
}
declare module 'strong-soap/src/base.js' {
  declare module.exports: $Exports<'strong-soap/src/base'>;
}
declare module 'strong-soap/src/client.js' {
  declare module.exports: $Exports<'strong-soap/src/client'>;
}
declare module 'strong-soap/src/globalize.js' {
  declare module.exports: $Exports<'strong-soap/src/globalize'>;
}
declare module 'strong-soap/src/http.js' {
  declare module.exports: $Exports<'strong-soap/src/http'>;
}
declare module 'strong-soap/src/parser/element.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/element'>;
}
declare module 'strong-soap/src/parser/helper.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/helper'>;
}
declare module 'strong-soap/src/parser/index.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/index'>;
}
declare module 'strong-soap/src/parser/nscontext.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/nscontext'>;
}
declare module 'strong-soap/src/parser/qname.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/qname'>;
}
declare module 'strong-soap/src/parser/soap/body.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/soap/body'>;
}
declare module 'strong-soap/src/parser/soap/fault.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/soap/fault'>;
}
declare module 'strong-soap/src/parser/soap/header.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/soap/header'>;
}
declare module 'strong-soap/src/parser/soap/headerFault.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/soap/headerFault'>;
}
declare module 'strong-soap/src/parser/soap/soapElement.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/soap/soapElement'>;
}
declare module 'strong-soap/src/parser/soap12/body.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/soap12/body'>;
}
declare module 'strong-soap/src/parser/soap12/fault.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/soap12/fault'>;
}
declare module 'strong-soap/src/parser/soap12/header.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/soap12/header'>;
}
declare module 'strong-soap/src/parser/soap12/headerFault.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/soap12/headerFault'>;
}
declare module 'strong-soap/src/parser/soap12/soapElement.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/soap12/soapElement'>;
}
declare module 'strong-soap/src/parser/typeRegistry.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/typeRegistry'>;
}
declare module 'strong-soap/src/parser/wsdl.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl'>;
}
declare module 'strong-soap/src/parser/wsdl/binding.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/binding'>;
}
declare module 'strong-soap/src/parser/wsdl/definitions.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/definitions'>;
}
declare module 'strong-soap/src/parser/wsdl/documentation.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/documentation'>;
}
declare module 'strong-soap/src/parser/wsdl/fault.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/fault'>;
}
declare module 'strong-soap/src/parser/wsdl/import.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/import'>;
}
declare module 'strong-soap/src/parser/wsdl/input.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/input'>;
}
declare module 'strong-soap/src/parser/wsdl/message.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/message'>;
}
declare module 'strong-soap/src/parser/wsdl/operation.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/operation'>;
}
declare module 'strong-soap/src/parser/wsdl/output.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/output'>;
}
declare module 'strong-soap/src/parser/wsdl/parameter.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/parameter'>;
}
declare module 'strong-soap/src/parser/wsdl/part.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/part'>;
}
declare module 'strong-soap/src/parser/wsdl/port.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/port'>;
}
declare module 'strong-soap/src/parser/wsdl/portType.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/portType'>;
}
declare module 'strong-soap/src/parser/wsdl/service.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/service'>;
}
declare module 'strong-soap/src/parser/wsdl/types.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/types'>;
}
declare module 'strong-soap/src/parser/wsdl/wsdlElement.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/wsdl/wsdlElement'>;
}
declare module 'strong-soap/src/parser/xmlHandler.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xmlHandler'>;
}
declare module 'strong-soap/src/parser/xsd.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd'>;
}
declare module 'strong-soap/src/parser/xsd/all.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/all'>;
}
declare module 'strong-soap/src/parser/xsd/annotation.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/annotation'>;
}
declare module 'strong-soap/src/parser/xsd/any.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/any'>;
}
declare module 'strong-soap/src/parser/xsd/anyAttribute.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/anyAttribute'>;
}
declare module 'strong-soap/src/parser/xsd/attribute.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/attribute'>;
}
declare module 'strong-soap/src/parser/xsd/attributeGroup.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/attributeGroup'>;
}
declare module 'strong-soap/src/parser/xsd/choice.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/choice'>;
}
declare module 'strong-soap/src/parser/xsd/complexContent.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/complexContent'>;
}
declare module 'strong-soap/src/parser/xsd/complexType.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/complexType'>;
}
declare module 'strong-soap/src/parser/xsd/descriptor.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/descriptor'>;
}
declare module 'strong-soap/src/parser/xsd/documentation.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/documentation'>;
}
declare module 'strong-soap/src/parser/xsd/element.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/element'>;
}
declare module 'strong-soap/src/parser/xsd/extension.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/extension'>;
}
declare module 'strong-soap/src/parser/xsd/group.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/group'>;
}
declare module 'strong-soap/src/parser/xsd/import.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/import'>;
}
declare module 'strong-soap/src/parser/xsd/include.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/include'>;
}
declare module 'strong-soap/src/parser/xsd/key.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/key'>;
}
declare module 'strong-soap/src/parser/xsd/keybase.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/keybase'>;
}
declare module 'strong-soap/src/parser/xsd/keyref.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/keyref'>;
}
declare module 'strong-soap/src/parser/xsd/list.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/list'>;
}
declare module 'strong-soap/src/parser/xsd/restriction.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/restriction'>;
}
declare module 'strong-soap/src/parser/xsd/schema.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/schema'>;
}
declare module 'strong-soap/src/parser/xsd/sequence.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/sequence'>;
}
declare module 'strong-soap/src/parser/xsd/simpleContent.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/simpleContent'>;
}
declare module 'strong-soap/src/parser/xsd/simpleType.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/simpleType'>;
}
declare module 'strong-soap/src/parser/xsd/union.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/union'>;
}
declare module 'strong-soap/src/parser/xsd/unique.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/unique'>;
}
declare module 'strong-soap/src/parser/xsd/xsdElement.js' {
  declare module.exports: $Exports<'strong-soap/src/parser/xsd/xsdElement'>;
}
declare module 'strong-soap/src/security/BasicAuthSecurity.js' {
  declare module.exports: $Exports<'strong-soap/src/security/BasicAuthSecurity'>;
}
declare module 'strong-soap/src/security/BearerSecurity.js' {
  declare module.exports: $Exports<'strong-soap/src/security/BearerSecurity'>;
}
declare module 'strong-soap/src/security/ClientSSLSecurity.js' {
  declare module.exports: $Exports<'strong-soap/src/security/ClientSSLSecurity'>;
}
declare module 'strong-soap/src/security/ClientSSLSecurityPFX.js' {
  declare module.exports: $Exports<'strong-soap/src/security/ClientSSLSecurityPFX'>;
}
declare module 'strong-soap/src/security/index.js' {
  declare module.exports: $Exports<'strong-soap/src/security/index'>;
}
declare module 'strong-soap/src/security/NTLMSecurity.js' {
  declare module.exports: $Exports<'strong-soap/src/security/NTLMSecurity'>;
}
declare module 'strong-soap/src/security/security.js' {
  declare module.exports: $Exports<'strong-soap/src/security/security'>;
}
declare module 'strong-soap/src/security/WSSecurity.js' {
  declare module.exports: $Exports<'strong-soap/src/security/WSSecurity'>;
}
declare module 'strong-soap/src/security/WSSecurityCert.js' {
  declare module.exports: $Exports<'strong-soap/src/security/WSSecurityCert'>;
}
declare module 'strong-soap/src/server.js' {
  declare module.exports: $Exports<'strong-soap/src/server'>;
}
declare module 'strong-soap/src/soap.js' {
  declare module.exports: $Exports<'strong-soap/src/soap'>;
}
declare module 'strong-soap/src/soapModel.js' {
  declare module.exports: $Exports<'strong-soap/src/soapModel'>;
}
declare module 'strong-soap/src/strip-bom.js' {
  declare module.exports: $Exports<'strong-soap/src/strip-bom'>;
}
declare module 'strong-soap/src/utils.js' {
  declare module.exports: $Exports<'strong-soap/src/utils'>;
}
